import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Footer, Header } from "@/components/global";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Sistema de consultas de citas médicas",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					"bg-background font-sans antialiased container mx-auto",
					fontSans.variable
				)}
			>
				<div className='grid grid-rows-[auto_1fr_auto] min-h-dvh'>
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
